from time import sleep
from selenium import webdriver

webDriver = webdriver.Chrome()
print("打开百度")
webDriver.get('https://www.baidu.com/')
sleep(2)
print("打开微信读书")
webDriver.get('https://weread.qq.com/')
print("窗口的大小：")
print(webDriver.get_window_size())
print(type(webDriver.get_window_size()))
print("窗口的位置：")
print(webDriver.get_window_position())
print(type(webDriver.get_window_position()))
sleep(2)
print("设置窗口的位置")
webDriver.set_window_position(500, 300)
print("新窗口的位置：")
print(webDriver.get_window_position())
sleep(2)
print("网页的标题："+webDriver.title)
sleep(2)
print("窗口最大化")
webDriver.maximize_window()
print("窗口回退")
webDriver.back()
sleep(2)
print("当前窗口句柄：")
print(webDriver.current_window_handle)
webDriver.find_element_by_link_text("新闻").click()
print("所有句柄：")
print(webDriver.window_handles)
sleep(2)
webDriver.close()
print("现在所有句柄：")
print(webDriver.window_handles)
sleep(2)
webDriver.quit()
